---
- hosts: all
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/win_firewall_rule_module.html#win-firewall-rule-module
  - name: Firewall rule to allow RDP on TCP port 3389
    win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      profiles: private
      state: present
      enabled: yes

  - name: Firewall rule to allow ICMP v4 (ping)
    win_firewall_rule:
      name: ICMP Allow incoming V4 echo request
      enabled: yes
      state: present
      profiles: private
      action: allow
      direction: in
      protocol: icmpv4
